### PR TITLE
Cardano Method

### PR DESCRIPTION
**Pull request by rodolfomiranda**

### CODE REVIEW

**Comment by swcurran** [comment]
Thanks for the entry.  Looks like the .gitignore is not working as expected. In the meantime, can you please remove the `index.html`, `package-lock.json` and `.DS-store` from the PR?  Thanks.

**Review by swcurran — APPROVED** [review]

**Comment by swcurran** [comment]
Arrggh...I didn't realize that DCO was not signed.  DCO - Developer Certificate of Origin - https://github.com/apps/dco.  Click "details" above.  Sorry about that.

**Comment by rodolfomiranda** [comment]
it was signed, but when I deleted the files from GitHub portal directly, it failed again. Let me fix it.

**Comment by rodolfomiranda** [comment]
Fixed. The `index.html` shows as to be deleted. Is that OK? will it be regenerated at rendering actions?

**Pull request merged**
